
default: &default
  adapter: postgresql
  encoding: unicode
  username: fang
  password: 123456
  host: localhost
  port: 5001
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  # 继承
  <<: *default
  database: projectName_development
test:
  <<: *default
  database: projectName_test
production:
  <<: *default
  database: projectName_production
  username: projectName
  password: <%= ENV['PROJECTNAME_DATABASE_PASSWORD'] %>
